DROP DATABASE IF EXISTS SW;
CREATE DATABASE IF NOT EXISTS SW;

USE SW;

CREATE TABLE CHARACTERS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
GENDER VARCHAR(50),
SKIN_COLOR VARCHAR(50),
HOMEWORLD VARCHAR(20),
HAIR_COLOR VARCHAR(50)
);