DROP DATABASE IF EXISTS SWLogin;
CREATE DATABASE IF NOT EXISTS SWLogin;

USE SWLogin;

drop table if exists USUARIOS;
CREATE TABLE IF NOT EXISTS USUARIOS(
USUARIO VARCHAR(50),
PASS VARCHAR(255),

primary key(usuario)
);

/*insert into USUARIOS(USUARIO,PASS) VALUES ("ADMIN","renaido")*/

