DROP DATABASE IF EXISTS SWLogin;
CREATE DATABASE IF NOT EXISTS SWLogin;

USE SWLogin;

drop table if exists USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
USUARIO VARCHAR(50),
PASS VARCHAR(50)
);

